# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ main ]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: generate lock files
        run: yarn
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: yarn
      - name: get list
        run: |
          yarn list > yarn.list
      - uses: actions/upload-artifact@v2
        with:
          name: prepare
          path: |
            ./yarn.list
            ./yarn.lock

  # This workflow contains a single job called "build"
  build:
    needs: [prepare]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # do a matrix test with different node versions
    strategy:
      fail-fast: false
      matrix:
        node-version: [ lts/*, 16]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: prepare
          path: .
      # try to perform a nodejs setup
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: npm install, build, and test
        run: |
          yarn install
          yarn build
          echo start tests
        env:
          CI: true
      - uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
        with:
          test-command: yarn run test:CI:coverage
          coverage-comment: false

      - name: replace path in coverage files
        run: find ./coverage -type f -exec sed -i -e "s@$(pwd)@<root>@g" {} \;
        if: always()

      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: |
            ./coverage/clover.xml
            ./coverage/coverage-final.json
            ./coverage/lcov.info
            ./coverage/junit.xml
            ./coverage/test-report.xml
        if: always()


  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install eslint
        run: npm install
      - name: run eslint
        run: |
          echo start eslint
          mkdir coverage
          npm run ci:eslint
        continue-on-error: true
        env:
          CI: true

      - name: replace path in coverage files
        run: find ./coverage -type f -exec sed -i -e "s@$(pwd)@<root>@g" {} \;

      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage/eslint-report.json