name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - docker/README.md
      - .github/workflows/dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.event.repository.full_name }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./docker/README.md
